name: sql-ci

on:
  push:
    branches: [ main ]

jobs:
  Setup:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    steps:
      - name: Install MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'

      - name: Verify MySQL Installation
        run: mysql -uroot -h127.0.0.1 -e 'SELECT version()'
    
  Create-schema:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files from repo
        uses: actions/checkout@v3

      - name: Setup Data
        run: |
          mysql -u root  -h127.0.0.1 mysql < schema.sql
          mysql -u root  -h127.0.0.1 mysql < data.sql

      - name: Run tests
        run: |
          mysql -u root  -h127.0.0.1 mysql < tests.sql

          # Check the output of tests and fail the build if necessary
          if [ $? -ne 0 ]; then
            echo "Tests failed. Aborting deployment."
            exit 1
          fi  