name: sql-ci

on:
  push:
    branches: [ main ]

jobs:
  MySQL-Setup:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    steps:
      - name: Install MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'

      - name: Verify MySQL Installation
        run: mysql -uroot -h127.0.0.1 -e 'SELECT version()'
    
      - name: Checkout Files from repo
        uses: actions/checkout@v3

      - name: List Workspace folder
        run: |
            pwd
            ls
            
      - name: Setup Data
        run: |
          mysql -u root  -h127.0.0.1 mysql < schema.sql
          mysql -u root  -h127.0.0.1 mysql < data.sql
          mysql -u root  -h127.0.0.1 mysql < sp.sql

      - name: Run tests
        run: |
          mysql -u root  -h127.0.0.1 mysql < tests.sql

          # Check the output of tests and fail the build if necessary
          if [ $? -ne 0 ]; then
            echo "Tests failed. Aborting deployment."
            exit 1
          fi

      - name: Insert using SP
        run: |
          mysql -u root  -h127.0.0.1 mysql -se 'CALL sp_insert("Joey Tribianni","jtribianni@friends.com")'

      - name: Run Test using Shell
        run: bash test.sh